---
- hosts: peering
  tasks:
    - name: "Generate private key for this specific WireGuard connection"
      shell: "wg genkey > tee privkey"
      register: wg_priv

    - name: "Read public key from our randomly generated private key"
      shell: "wg pubkey < privkey"
      register: wg_pub 

    - name: "Get peering data for next server in line"
      template:
        src:
        dest:
      with_items:
        - "{{ groups[hostvars[ansible_hostname].peering_country] }}"
      when: groups[hostvars[ansible_hostname].peering_country} is not defined
    
    - name: ""
