---
- hosts: peering
  tasks:
    - name: "Get all the peer data into a variable"
      include_vars: 
        name: peers
        file: vars/peers/{{hostvars[inventory_hostname].peering_country}}-wg.yml

    - name: "Generate WireGuard configuration for systemd-networkd" # This is for WireGuard solutions.
      include_tasks: handlers/wg-conf.yml
      with_dict: "{{ peers }}"
      when: (item.value.unique is not defined) or (item.value.unique == true and item.value.unique_host == inventory_hostname)

    - name: "Generate BIRD configuration"
      include_tasks: handlers/bird4.yml
      with_dict: "{{ peers }}"
      when: (item.value.unique is not defined) or (item.value.unique == true and item.value.unique_host == inventory_hostname) # Only for that one peering server, there's gotta be a better way to do this.

    - name: "Reconfiguring bird"
      shell: "birdc configure"
