# Generate WireGuard config in systemd-networkd
---
- name: "Generating netdev config file for {{item.value.peer_name}}"
  template:
    src: tpl/netdev.j2
    dest: /etc/systemd/network/{{item.value.peer_name}}.netdev

- name: "Generating network config file for {{item.value.peer_name}}"
  template:
    src: tpl/network.j2
    dest: /etc/systemd/network/{{item.value.peer_name}}.network

- name: "Restarting systemd-networkd"
  systemd:
    name: systemd-networkd
    state: restarted

- name: "Get priority using ruby script"
  shell: "ruby /root/bgp-community.rb {{item.value.peeringip}} 1000 encrypted"
  register: priority_peering

- name: "Generating bird4 configuration for {{item.value.peer_name}}"
  template:
    src: tpl/bird4.j2
    dest: /etc/bird/peer4/{{item.value.peer_name}}.conf
  when: item.value.ip_type == "ipv4"
