# Generate WireGuard config in systemd-networkd
---
- name: "Generating netdev config file for {{item.value.peer_name}}"
  template:
    src: tpl/wg/netdev.j2
    dest: /etc/systemd/network/{{item.value.peer_name}}.netdev

- name: "Generating network config file for {{item.value.peer_name}}"
  template:
    src: tpl/wg/network.j2
    dest: /etc/systemd/network/{{item.value.peer_name}}.network

- name: "Restarting systemd-networkd"
  systemd:
    name: systemd-networkd
    state: restarted

